####################### PHOEBUS preferences ########################

# Welcome
org.phoebus.ui/welcome=file:/opt/css/nasa-phoebus/products/nasa-beamlines/target/doc/welcome/welcome.html

#layouts
org.phoebus.ui/layout_dir=

# Preferences for the phoebus framework and apps
org.phoebus.ui/ui_monitor_period=0

# Save credentails so that they needed to be entered once
org.phoebus.ui/save_credentials=true

# Channel Access
org.phoebus.pv.ca/addr_list=192.168.83.255
org.phoebus.pv.ca/auto_addr_list=false

org.phoebus.pv.ca/dbe_property_supported=true
org.phoebus.pv.ca/variable_length_array=true

# PVAccess
org.epics.pva/EPICS_PVA_ADDR_LIST=192.168.83.255

# Subtle shading
org.csstudio.javafx.rtplot/shady_future=128, 128, 128, 10

# PV throttle (250)
org.csstudio.display.builder.runtime/update_throttle=250

# Display hesitation to accumulate updates (20)
org.csstudio.display.builder.representation/update_accumulation_time = 20
# Pause after updates (100)
org.csstudio.display.builder.representation/update_delay = 100
# Line Plot update throttle
org.csstudio.display.builder.representation/plot_update_delay = 250
# Image plot update throttle
org.csstudio.display.builder.representation/image_update_delay = 250


# Display Builder
org.phoebus.ui/top_resources=/opi/mdas-main.bob, NASA MDAS Main
org.phoebus.ui/home_display=/opi/mdas-main.bob, NASA MDAS Main

org.csstudio.display.builder.runtime/probe_display=
org.csstudio.display.builder.runtime/python_path=

#org.csstudio.display.converter.edm/auto_converter_dir=$(user.home)/phoebus_converter_output
#org.csstudio.display.converter.edm/colors_list=/opt/css/preferences/configuration/edm/colors.list

# Phoebus Alarm
org.phoebus.applications.alarm/server=localhost:9092
org.phoebus.applications.alarm/config_name=nasa_mdas_epics_alarm
org.phoebus.applications.alarm/config_names=nasa_mdas_epics_alarm
org.phoebus.applications.alarm.logging.ui/service_uri=http://localhost:5050

# Logbook
org.phoebus.logbook/logbook_factory=olog-es
#org.phoebus.olog.api/olog_url=https://epics-services-nasa.nasa.gov:9191/Olog/resources
#org.phoebus.olog.es.api/olog_url=https://localhost:9191/Olog
org.phoebus.olog.es.api/olog_url=http://localhost:9090/Olog

# Channelfinder
org.phoebus.channelfinder/serviceURL=https://localhost:7171/ChannelFinder

# Archived Data
org.csstudio.trends.databrowser3/urls=pbraw://localhost:17668/retrieval
org.csstudio.trends.databrowser3/archives=pbraw://localhost:17668/retrieval
org.csstudio.trends.databrowser3/use_default_archives=false
# Include to get a prompt for newly started instance
org.csstudio.trends.databrowser3/prompt_for_raw_data_request = true
org.csstudio.trends.databrowser3/prompt_for_visibility = true

# Save Restore
org.phoebus.applications.saveandrestore.client/jmasar.service.url=http://localhost:6060/save-restore
